
name: Video Classification
description: Perform video action classification using pre-trained models. 
author: Cloudera Inc.
specification_version: 1.0
prototype_version: 1.0
date: "2021-12-17"
api_version: 1

runtimes:
  - editor: Workbench
    kernel: Python 3.6
    edition: Standard
    version: 2021.09

engine_images:
  - image_name: engine
    tags:
      - 14-cml-2021.05-1
    
tasks:
  - type: run_session
    name: Install Dependencies
    script: cml/install_dependencies.py
    kernel: python3
    memory: 8
    cpu: 1

  - type: run_session
    name: Download Data
    script: cml/download_data.py
    kernel: python3
    memory: 4
    cpu: 1